version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
#    depends_on:
#      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - /server/node_modules
#    depends_on:
#      - postgres-db

  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: