version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
#    depends_on:
#      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - /server/node_modules
#    depends_on:
#      - database